

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    ports:
      - "3000:3000"
      
    environment:
      HOST: ${HOST}
      PORT: ${PORT}
      DB_USERNAME: ${DB_USERNAME}
      PASSWORD: ${PASSWORD}
      DATABASE: ${DATABASE}
      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
      cookieKey: ${cookieKey}
      NODE_ENV: ${NODE_ENV}
      FRONTEND_URL: ${FRONTEND_URL}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASS: ${EMAIL_PASS}
      MP_ACCESS_TOKEN: ${MP_ACCESS_TOKEN}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      ADMIN_RUT: ${ADMIN_RUT}
      BACKEND_URL: ${BACKEND_URL}

    depends_on:
      db:
        condition: service_healthy
    
    volumes:
      - ./backend:/app
      - /app/node_modules

    restart: unless-stopped
    networks:
      - vibra-network

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: ${DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped  
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DATABASE}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - vibra-network
 
  frontend:
    build:
      context: ./frontend

    volumes:
    - ./frontend:/app
    - /app/node_modules

    ports:
      - "5173:5173"

    depends_on:
      - backend
    networks:
      - vibra-network

volumes:
  postgres_data:

networks:
  vibra-network:
